"""empty message

Revision ID: 2b7d79864205
Revises: e7a8fa0231a2
Create Date: 2025-03-06 22:20:29.787103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7d79864205'
down_revision = 'e7a8fa0231a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Enum('True', 'False'), server_default='False', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
