"""empty message

Revision ID: e7a8fa0231a2
Revises: 
Create Date: 2025-03-04 16:47:55.038333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a8fa0231a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_firstname', sa.String(length=100), nullable=False),
    sa.Column('admin_lastname', sa.String(length=100), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('admin_phone_number', sa.String(length=20), nullable=False),
    sa.Column('admin_image', sa.String(length=255), nullable=True),
    sa.Column('admin_login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('customer',
    sa.Column('cust_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_firstname', sa.String(length=255), nullable=False),
    sa.Column('cust_lastname', sa.String(length=255), nullable=False),
    sa.Column('cust_password', sa.String(length=255), nullable=False),
    sa.Column('cust_email', sa.String(length=255), nullable=False),
    sa.Column('cust_phone_number', sa.String(length=20), nullable=False),
    sa.Column('cust_image', sa.String(length=255), nullable=True),
    sa.Column('cust_bill_address', sa.String(length=255), nullable=False),
    sa.Column('cust_status', sa.Enum('active', 'disabled'), server_default='active', nullable=True),
    sa.Column('cust_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cust_id'),
    sa.UniqueConstraint('cust_email')
    )
    op.create_table('driver',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_full_name', sa.String(length=255), nullable=False),
    sa.Column('driver_phone_number', sa.String(length=20), nullable=False),
    sa.Column('driver_email', sa.String(length=255), nullable=False),
    sa.Column('driver_license_number', sa.String(length=50), nullable=False),
    sa.Column('driver_status', sa.Enum('available', 'on_trip', 'inactive', name='driver_status'), nullable=True),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('driver_email'),
    sa.UniqueConstraint('driver_license_number')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=255), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=255), nullable=False),
    sa.Column('vehicle_plate_num', sa.String(length=50), nullable=False),
    sa.Column('vehicle_status', sa.Enum('available', 'in_use', 'maintenance'), server_default='available', nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vehicle_plate_num')
    )
    op.create_table('shipping',
    sa.Column('ship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_fees_amt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ship_state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('assignment',
    sa.Column('assign_id', sa.Integer(), nullable=False),
    sa.Column('assign_ship_id', sa.Integer(), nullable=False),
    sa.Column('assign_driver_id', sa.Integer(), nullable=False),
    sa.Column('assign_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assign_status', sa.Enum('assigned', 'in_transit', 'completed', 'cancelled'), server_default='assigned', nullable=True),
    sa.Column('assign_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assign_driver_id'], ['driver.driver_id'], ),
    sa.ForeignKeyConstraint(['assign_ship_id'], ['shipping.ship_id'], ),
    sa.ForeignKeyConstraint(['assign_vehicle_id'], ['vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('assign_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled'), server_default='pending', nullable=True),
    sa.Column('order_total_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_cust_id', sa.Integer(), nullable=False),
    sa.Column('order_ship_id', sa.Integer(), nullable=False),
    sa.Column('order_state_id', sa.Integer(), nullable=False),
    sa.Column('order_reference_no', sa.String(length=255), nullable=True),
    sa.Column('order_created_at', sa.DateTime(), nullable=True),
    sa.Column('order_payment_status', sa.Enum('pending', 'paid', 'failed'), server_default='pending', nullable=True),
    sa.ForeignKeyConstraint(['order_cust_id'], ['customer.cust_id'], ),
    sa.ForeignKeyConstraint(['order_ship_id'], ['shipping.ship_id'], ),
    sa.ForeignKeyConstraint(['order_state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_reference_no')
    )
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_method', sa.String(length=255), nullable=True),
    sa.Column('pay_status', sa.Enum('successful', 'pending', 'declined'), server_default='pending', nullable=True),
    sa.Column('pay_reference', sa.String(length=255), nullable=True),
    sa.Column('pay_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pay_order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('pay_id'),
    sa.UniqueConstraint('pay_reference')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('order')
    op.drop_table('assignment')
    op.drop_table('shipping')
    op.drop_table('vehicle')
    op.drop_table('state')
    op.drop_table('driver')
    op.drop_table('customer')
    op.drop_table('administrator')
    # ### end Alembic commands ###
